"""
Dandelion-Optimized Naive Bayes for Phishing Email Detection

This module implements the Dandelion optimization algorithm to optimize
Naive Bayes hyperparameters for phishing detection.

The Dandelion algorithm is a nature-inspired metaheuristic that mimics
the dispersal of dandelion seeds. It combines exploratory and exploitative
strategies to search the parameter space effectively.
"""

import os
import time
import joblib
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


class DandelionOptimizer:
    """
    Dandelion Optimization Algorithm for hyperparameter tuning.

    Inspired by how dandelion seeds disperse:
    1. Long-distance dispersal (exploration)
    2. Short-distance dispersal (exploitation)
    3. Selection based on fitness
    """

    def __init__(self, population_size=20, max_iter=50, random_state=42):
        """
        Initialize Dandelion optimizer.

        Args:
            population_size: Number of dandelion seeds (solutions)
            max_iter: Maximum iterations
            random_state: Random state for reproducibility
        """
        self.population_size = population_size
        self.max_iter = max_iter
        self.random_state = random_state
        np.random.seed(random_state)

        # Parameter search space for Naive Bayes
        self.alpha_range = (0.01, 2.0)  # Laplace smoothing
        self.fit_prior_options = [True, False]

    def generate_seed(self):
        """
        Generate a random dandelion seed (parameter combination).

        Returns:
            dict: Random parameter combination
        """
        seed = {
            'alpha': np.random.uniform(self.alpha_range[0], self.alpha_range[1]),
            'fit_prior': np.random.choice(self.fit_prior_options)
        }
        return seed

    def long_distance_dispersal(self, best_seed):
        """
        Long-distance dispersal phase (exploration).

        Seeds travel far to explore new regions of the search space.

        Args:
            best_seed: Best seed found so far

        Returns:
            list: New seeds generated by long-distance dispersal
        """
        new_seeds = []

        for _ in range(self.population_size // 2):
            # Add large random perturbation to explore new areas
            seed = {
                'alpha': best_seed['alpha'] + np.random.uniform(-0.5, 0.5),
                'fit_prior': np.random.choice(self.fit_prior_options)
            }

            # Ensure alpha is within bounds
            seed['alpha'] = np.clip(seed['alpha'], self.alpha_range[0], self.alpha_range[1])
            new_seeds.append(seed)

        return new_seeds

    def short_distance_dispersal(self, best_seed):
        """
        Short-distance dispersal phase (exploitation).

        Seeds travel short distances to refine promising solutions.

        Args:
            best_seed: Best seed found so far

        Returns:
            list: New seeds generated by short-distance dispersal
        """
        new_seeds = []

        for _ in range(self.population_size // 2):
            # Add small random perturbation to refine solution
            seed = {
                'alpha': best_seed['alpha'] + np.random.uniform(-0.1, 0.1),
                'fit_prior': np.random.choice([best_seed['fit_prior'], np.random.choice(self.fit_prior_options)], p=[0.8, 0.2])
            }

            # Ensure alpha is within bounds
            seed['alpha'] = np.clip(seed['alpha'], self.alpha_range[0], self.alpha_range[1])
            new_seeds.append(seed)

        return new_seeds

    def evaluate_fitness(self, seed, X_train, y_train, X_val, y_val):
        """
        Evaluate the fitness of a seed (parameter combination).

        Args:
            seed: Parameter combination
            X_train: Training features
            y_train: Training labels
            X_val: Validation features
            y_val: Validation labels

        Returns:
            float: Fitness score (F1-score)
        """
        # Train Naive Bayes with given parameters
        model = MultinomialNB(alpha=seed['alpha'], fit_prior=seed['fit_prior'])
        model.fit(X_train, y_train)

        # Predict on validation set
        y_pred = model.predict(X_val)

        # Calculate F1-score as fitness
        fitness = f1_score(y_val, y_pred)

        return fitness

    def optimize(self, X_train, y_train, X_val, y_val):
        """
        Run Dandelion optimization to find best hyperparameters.

        Args:
            X_train: Training features
            y_train: Training labels
            X_val: Validation features
            y_val: Validation labels

        Returns:
            dict: Best parameters found
        """
        logger.info(f"Starting Dandelion optimization (population={self.population_size}, iterations={self.max_iter})")

        # Initialize population
        population = [self.generate_seed() for _ in range(self.population_size)]

        # Evaluate initial population
        fitness_scores = []
        for seed in population:
            fitness = self.evaluate_fitness(seed, X_train, y_train, X_val, y_val)
            fitness_scores.append(fitness)

        # Find best seed
        best_idx = np.argmax(fitness_scores)
        best_seed = population[best_idx]
        best_fitness = fitness_scores[best_idx]

        logger.info(f"Iteration 0: Best F1 = {best_fitness:.4f}, alpha={best_seed['alpha']:.4f}, fit_prior={best_seed['fit_prior']}")

        # Iterate
        for iteration in range(self.max_iter):
            # Generate new population
            new_seeds = []

            # Long-distance dispersal (exploration)
            long_distance_seeds = self.long_distance_dispersal(best_seed)
            new_seeds.extend(long_distance_seeds)

            # Short-distance dispersal (exploitation)
            short_distance_seeds = self.short_distance_dispersal(best_seed)
            new_seeds.extend(short_distance_seeds)

            # Evaluate new seeds
            new_fitness_scores = []
            for seed in new_seeds:
                fitness = self.evaluate_fitness(seed, X_train, y_train, X_val, y_val)
                new_fitness_scores.append(fitness)

            # Combine old and new populations, select best
            all_seeds = population + new_seeds
            all_fitness = fitness_scores + new_fitness_scores

            # Select top seeds
            sorted_indices = np.argsort(all_fitness)[::-1][:self.population_size]
            population = [all_seeds[i] for i in sorted_indices]
            fitness_scores = [all_fitness[i] for i in sorted_indices]

            # Update best
            if fitness_scores[0] > best_fitness:
                best_seed = population[0]
                best_fitness = fitness_scores[0]

            logger.info(f"Iteration {iteration+1}: Best F1 = {best_fitness:.4f}, alpha={best_seed['alpha']:.4f}, fit_prior={best_seed['fit_prior']}")

        logger.info(f"Optimization complete. Best F1 = {best_fitness:.4f}")
        logger.info(f"Best parameters: alpha={best_seed['alpha']:.4f}, fit_prior={best_seed['fit_prior']}")

        return best_seed, best_fitness


class DandelionNaiveBayesDetector:
    """Naive Bayes classifier optimized with Dandelion algorithm."""

    def __init__(self, population_size=20, max_iter=50, random_state=42):
        """
        Initialize Dandelion-optimized Naive Bayes.

        Args:
            population_size: Number of seeds in Dandelion optimization
            max_iter: Maximum iterations in Dandelion optimization
            random_state: Random state for reproducibility
        """
        self.model = None
        self.alpha = None
        self.fit_prior = None
        self.population_size = population_size
        self.max_iter = max_iter
        self.random_state = random_state
        self.training_time = None
        self.inference_time = None
        self.optimization_time = None

    def optimize_parameters(self, X_train, y_train):
        """
        Optimize hyperparameters using Dandelion algorithm.

        Args:
            X_train: Training features
            y_train: Training labels

        Returns:
            dict: Best parameters found
        """
        logger.info("Starting hyperparameter optimization with Dandelion algorithm...")

        # Split training data for validation
        from sklearn.model_selection import train_test_split
        X_opt_train, X_opt_val, y_opt_train, y_opt_val = train_test_split(
            X_train, y_train, test_size=0.2, random_state=self.random_state, stratify=y_train
        )

        # Run Dandelion optimization
        start_time = time.time()
        optimizer = DandelionOptimizer(
            population_size=self.population_size,
            max_iter=self.max_iter,
            random_state=self.random_state
        )
        best_params, best_fitness = optimizer.optimize(X_opt_train, y_opt_train, X_opt_val, y_opt_val)
        self.optimization_time = time.time() - start_time

        # Store best parameters
        self.alpha = best_params['alpha']
        self.fit_prior = best_params['fit_prior']

        logger.info(f"Optimization complete in {self.optimization_time:.2f} seconds")
        logger.info(f"Best parameters: alpha={self.alpha:.4f}, fit_prior={self.fit_prior}")

        return best_params

    def train(self, X_train, y_train):
        """
        Train the optimized Naive Bayes model.

        Args:
            X_train: Training features
            y_train: Training labels

        Returns:
            self: Trained model
        """
        logger.info("Training Dandelion-optimized Naive Bayes...")

        # Optimize parameters if not already done
        if self.alpha is None or self.fit_prior is None:
            self.optimize_parameters(X_train, y_train)

        # Train model with optimized parameters
        start_time = time.time()
        self.model = MultinomialNB(alpha=self.alpha, fit_prior=self.fit_prior)
        self.model.fit(X_train, y_train)
        self.training_time = time.time() - start_time

        logger.info(f"Training complete in {self.training_time:.2f} seconds")

        return self

    def predict(self, X_test):
        """
        Make predictions on test data.

        Args:
            X_test: Test features

        Returns:
            np.ndarray: Predictions
        """
        start_time = time.time()
        predictions = self.model.predict(X_test)
        self.inference_time = time.time() - start_time

        logger.info(f"Prediction complete in {self.inference_time:.2f} seconds ({len(predictions)} samples)")

        return predictions

    def predict_proba(self, X_test):
        """
        Get prediction probabilities.

        Args:
            X_test: Test features

        Returns:
            np.ndarray: Prediction probabilities
        """
        return self.model.predict_proba(X_test)

    def evaluate(self, X_test, y_test):
        """
        Evaluate the model on test data.

        Args:
            X_test: Test features
            y_test: True labels

        Returns:
            dict: Evaluation metrics
        """
        logger.info("Evaluating model...")

        predictions = self.predict(X_test)

        # Calculate metrics
        accuracy = accuracy_score(y_test, predictions)
        precision = precision_score(y_test, predictions)
        recall = recall_score(y_test, predictions)
        f1 = f1_score(y_test, predictions)

        metrics = {
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'training_time': self.training_time,
            'inference_time': self.inference_time,
            'optimization_time': self.optimization_time,
            'total_time': self.optimization_time + self.training_time if self.optimization_time else self.training_time,
            'alpha': self.alpha,
            'fit_prior': self.fit_prior
        }

        logger.info(f"Accuracy: {accuracy:.4f}")
        logger.info(f"Precision: {precision:.4f}")
        logger.info(f"Recall: {recall:.4f}")
        logger.info(f"F1-Score: {f1:.4f}")

        return metrics

    def save_model(self, filepath):
        """
        Save trained model to file.

        Args:
            filepath: Path to save the model
        """
        model_data = {
            'model': self.model,
            'alpha': self.alpha,
            'fit_prior': self.fit_prior,
            'random_state': self.random_state,
            'training_time': self.training_time,
            'optimization_time': self.optimization_time
        }

        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        joblib.dump(model_data, filepath)
        logger.info(f"Model saved to {filepath}")

    def load_model(self, filepath):
        """
        Load trained model from file.

        Args:
            filepath: Path to load the model from

        Returns:
            self: Loaded model
        """
        model_data = joblib.load(filepath)

        self.model = model_data['model']
        self.alpha = model_data['alpha']
        self.fit_prior = model_data['fit_prior']
        self.random_state = model_data['random_state']
        self.training_time = model_data['training_time']
        self.optimization_time = model_data['optimization_time']

        logger.info(f"Model loaded from {filepath}")

        return self


def train_dandelion_nb(X_train=None, X_test=None, y_train=None, y_test=None, population_size=20, max_iter=50):
    """
    Convenience function to train and evaluate Dandelion-optimized Naive Bayes.

    Args:
        X_train: Training features
        X_test: Test features
        y_train: Training labels
        y_test: Test labels
        population_size: Population size for Dandelion optimization
        max_iter: Maximum iterations for Dandelion optimization

    Returns:
        tuple: Trained model and evaluation metrics
    """
    if X_train is None or X_test is None or y_train is None or y_test is None:
        # If data not provided, load and preprocess
        import sys
        sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
        from data_preprocessing import DataPreprocessor

        logger.info("Loading and preprocessing data...")
        preprocessor = DataPreprocessor(max_features=5000, random_state=42)
        df = preprocessor.download_dataset()
        df = preprocessor.preprocess_dataframe(df)
        X_train, X_test, y_train, y_test = preprocessor.split_for_ml(df, test_size=0.3)

    # Initialize and train model
    dandelion_nb = DandelionNaiveBayesDetector(
        population_size=population_size,
        max_iter=max_iter,
        random_state=42
    )
    dandelion_nb.train(X_train, y_train)

    # Evaluate model
    metrics = dandelion_nb.evaluate(X_test, y_test)

    # Save model
    models_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'models')
    model_path = os.path.join(models_dir, 'dandelion_nb_model.pkl')
    dandelion_nb.save_model(model_path)

    logger.info("\n" + "="*50)
    logger.info("DANDELION-OPTIMIZED NAIVE BAYES RESULTS")
    logger.info("="*50)
    logger.info(f"Optimized Parameters:")
    logger.info(f"  alpha = {metrics['alpha']:.4f}")
    logger.info(f"  fit_prior = {metrics['fit_prior']}")
    logger.info(f"\nPerformance Metrics:")
    logger.info(f"  Accuracy:  {metrics['accuracy']:.4f}")
    logger.info(f"  Precision: {metrics['precision']:.4f}")
    logger.info(f"  Recall:    {metrics['recall']:.4f}")
    logger.info(f"  F1-Score:  {metrics['f1_score']:.4f}")
    logger.info(f"\nTiming:")
    logger.info(f"  Optimization Time: {metrics['optimization_time']:.2f} seconds")
    logger.info(f"  Training Time:      {metrics['training_time']:.2f} seconds")
    logger.info(f"  Inference Time:     {metrics['inference_time']:.2f} seconds")
    logger.info(f"  Total Time:         {metrics['total_time']:.2f} seconds")
    logger.info("="*50)

    return dandelion_nb, metrics


if __name__ == "__main__":
    model, metrics = train_dandelion_nb(population_size=20, max_iter=50)
